version: '3.8'

services:

  nginx:
    build: ./infra/production/nginx
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 80:80
      - 443:443
      - 5555:5555
    depends_on:
      - web
      - flower

  web:
    build:
      context: .
      dockerfile: infra/production/django/Dockerfile
    command: /start
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: infra/production/django/Dockerfile
    image: walter_celery_worker
    command: /start-celeryworker
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: infra/production/django/Dockerfile
    image: walter_celery_beat
    command: /start-celerybeat
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: infra/production/django/Dockerfile
    image: walter_celery_flower
    command: /start-flower
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
      - flower_db:/app/flower_db
    env_file:
      - .env
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
  staticfiles:
  mediafiles:
  flower_db: