[tool.poetry]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = ["Mikhail Ivanov <ya.ivanov-m2014@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.6"
ruff = "^0.4.8"

[tool.ruff]
target-version = "py310"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
