server {
      listen 80;
      server_name _;

      location /static/ {
          alias /app/staticfiles/;
          access_log off;
          expires 7d;
          add_header Cache-Control "public, max-age=604800";
      }

      location /media/ {
          alias /app/mediafiles/;
          access_log off;
          expires 1d;
          add_header Cache-Control "public, max-age=86400";
      }

      location / {
          return 404;
      }
}