# Generated by Django 5.0.6 on 2024-06-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='guid',
        ),
    ]
