# Generated by Django 5.0.6 on 2024-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='hidden_feeds',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hidden_feed_items',
            field=models.ManyToManyField(blank=True, to='feed.feeditem'),
        ),
    ]
