# Generated by Django 5.0.6 on 2024-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_usersettings_hidden_feeds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
