# Generated by Django 5.0.6 on 2024-07-03 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_waitlistrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_sent',
            field=models.BooleanField(default=False),
        ),
    ]
