# Generated by Django 5.0.6 on 2024-07-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_waitlistrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
