# Generated by Django 5.0.6 on 2024-07-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_waitlistrequest_invite_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_accepted',
        ),
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_accepted_at',
        ),
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_activated',
        ),
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_activated_at',
        ),
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_sent',
        ),
        migrations.RemoveField(
            model_name='waitlistrequest',
            name='invite_sent_at',
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Activated', 'Activated')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waitlistrequest',
            name='invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.invite'),
        ),
    ]
