# Generated by Django 5.0.6 on 2024-07-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_feed_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='icon',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
