# Generated by Django 5.0.7 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_feeditem_has_paid_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='liked_feed_items',
            field=models.ManyToManyField(blank=True, related_name='liked', to='feed.feeditem'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='hidden_feed_items',
            field=models.ManyToManyField(blank=True, related_name='hidden', to='feed.feeditem'),
        ),
    ]
