# Generated by Django 5.0.7 on 2024-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_usersettings_liked_feed_items_alter_feeditem_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='rss_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
