# Generated by Django 5.0.7 on 2024-09-22 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_feed_rss_url_alter_feed_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='feed.feed'),
        ),
        migrations.CreateModel(
            name='ServiceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('podcasts', 'Podcast'), ('articles', 'Article'), ('videos', 'Videos')], default='liked', max_length=20)),
                ('feed_items', models.ManyToManyField(blank=True, related_name='service_feeds', to='feed.feeditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
