# Generated by Django 5.0.7 on 2024-09-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_alter_feeditem_feed_servicefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video'), ('embed', 'Embed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicefeed',
            name='type',
            field=models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], default='liked', max_length=20),
        ),
    ]
