# Generated by Django 5.1.3 on 2024-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_feeditem_preview_alter_feeditem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='preview',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
