# Generated by Django 5.1.3 on 2024-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='feed_items',
        ),
        migrations.AddField(
            model_name='collection',
            name='feeds',
            field=models.ManyToManyField(blank=True, to='feed.feed'),
        ),
    ]
