# Generated by Django 5.1.4 on 2024-12-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0029_collection_slug_collection_unique_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeed',
            name='type',
            field=models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('viewed', 'Viewed')], default='liked', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedItemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike'), (3, 'View')])),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='feed.feeditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed_item', 'type')},
            },
        ),
    ]
