# Generated by Django 5.1.4 on 2025-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_delete_servicefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='collections', to='feed.feed'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
