#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

gunicorn walter.wsgi:application --bind 0.0.0.0:8000 --workers 3