#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
django-admin compilemessages

python -m gunicorn walter.asgi:application -k walter.worker.WalterWorker --bind 0.0.0.0:8000 --workers 9